# Standards: 0.1
---
- name: Install required package
  apt:
    deb: "{{ graylog_sidecar_package }}"
    state: present
  tags:
    - graylog-sidecar

- name: Write config file
  notify:
    - Restart graylog-sidecar
  template:
    src: config.j2
    dest: /etc/graylog/sidecar/sidecar.yml
  tags:
    - graylog-sidecar

- name: Write service file
  notify:
    - Restart graylog-sidecar
  template:
    src: service.j2
    dest: /etc/systemd/system/graylog-sidecar.service
  tags:
    - graylog-sidecar

- name: Start graylog-sidecar service
  systemd:
    name: graylog-sidecar
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - graylog-sidecar

...
